from enum import auto, Enum


class Terminals(Enum):
    BEGIN = auto()
    IF = auto()
    THEN = auto()
    ELSE = auto()
    ENDIF = auto()
    WHILE = auto()
    DO = auto()
    WHILEEND = auto()
    END = auto()
    GT = auto()
    LT = auto()
    GTE = auto()
    LTE = auto()
    EQUALEQUALS = auto()
    NOTEQUAL = auto()
    INT = auto()
    FLOAT = auto()
    BOOL = auto()
    SEMICOLON = auto()
    COMMA = auto()
    ID = auto()
    NUM = auto()
    LEFT_PAREN = auto()
    RIGHT_PAREN = auto()
    EOF = auto()
    ADDITION = auto()
    SUBTRACTION = auto()
    MULTIPLICATION = auto()
    DIVISION = auto()
    ASSIGNEQUALS = auto()
    EPSILON = auto()


class NonTerminals(Enum):
    STATEMENT = auto()
    MORESTATEMENTS = auto()
    CONDITIONAL = auto()
    CONDITIONAL_PRIME = auto()
    DECLARATIVE = auto()
    TYPES = auto()
    MOREIDS = auto()
    ASSIGNMENT = auto()
    EXPRESSION = auto()
    EXPRESSION_PRIME = auto()
    TERM = auto()
    TERM_PRIME = auto()
    FACTOR = auto()
    RELATIONAL_OPERATOR = auto()
